# ФАЙЛ НЕ СОВПАДАЕТ С UI-ФАЙЛОМ!
# Form implementation generated from reading ui file 'forms/UI_forms/add_essay.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setGeometry(300, 20, 933, 787)
        MainWindow.setMinimumSize(QtCore.QSize(933, 753))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet(".QPushButton {\n"
                                 "    width: 100px;\n"
                                 "    height: 100px;\n"
                                 "    background-color:#e6ad85;\n"
                                 "    margin: 10px;\n"
                                 "    border-radius: 5px;\n"
                                 "    font-size:20px;\n"
                                 "    word-wrap: break-word;\n"
                                 "    cursor: Pointing-Hand;   \n"
                                 "}\n"
                                 ".QPushButton:hover {\n"
                                 "    background-color: rgb(201, 152, 117);\n"
                                 "}\n"
                                 ".QWidget {\n"
                                 "background-color: rgb(240, 221, 192);\n"
                                 "\n"
                                 "}\n"
                                 "* {font-family: Times New Roman;\n"
                                 "    font-size:14;}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.go_home_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.go_home_btn.setGeometry(QtCore.QRect(20, 20, 141, 61))
        self.go_home_btn.setObjectName("go_home_btn")
        self.title = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(180, 30, 741, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.title.setFont(font)
        self.title.setStyleSheet("font: 75 18pt \"Times New Roman\";")
        self.title.setText("")
        self.title.setObjectName("title")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 90, 931, 691))
        self.scrollArea.setStyleSheet("border:none;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -297, 910, 1138))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.essay_text = QtWidgets.QTextEdit(parent=self.widget)
        self.essay_text.setEnabled(True)
        self.essay_text.setMinimumSize(QtCore.QSize(700, 550))
        self.essay_text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.essay_text.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.essay_text.setObjectName("essay_text")
        self.verticalLayout.addWidget(self.essay_text)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.genre_combo_box = QtWidgets.QComboBox(parent=self.widget)
        self.genre_combo_box.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.genre_combo_box.setFont(font)
        self.genre_combo_box.setEditable(True)
        self.genre_combo_box.setObjectName("genre_combo_box")
        self.gridLayout_2.addWidget(self.genre_combo_box, 1, 0, 1, 1)
        self.genre_list = QtWidgets.QListWidget(parent=self.widget)
        self.genre_list.setObjectName("genre_list")
        self.genre_list.setFont(font)
        self.gridLayout_2.addWidget(self.genre_list, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.literature_combo_box = QtWidgets.QComboBox(parent=self.widget)
        self.literature_combo_box.setMinimumSize(QtCore.QSize(0, 40))
        self.literature_combo_box.setEditable(True)
        self.literature_combo_box.setFont(font)
        self.literature_combo_box.setObjectName("literature_combo_box")
        self.gridLayout.addWidget(self.literature_combo_box, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.literature_list = QtWidgets.QListWidget(parent=self.widget)
        self.literature_list.setObjectName("literature_list")
        self.literature_list.setFont(font)
        self.gridLayout.addWidget(self.literature_list, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        # Добавленные radiobuttons
        self.essay_type_layout = QtWidgets.QVBoxLayout()
        self.essay_type_layout.setObjectName("essay_type_layout")

        self.essay_type_label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.essay_type_label.setFont(font)
        self.essay_type_label.setObjectName("essay_type_label")
        self.essay_type_layout.addWidget(self.essay_type_label)

        self.radio_button_layout = QtWidgets.QHBoxLayout()
        self.radio_button_layout.setObjectName("radio_button_layout")

        self.ege_radio = QtWidgets.QRadioButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.ege_radio.setFont(font)
        self.ege_radio.setObjectName("ege_radio")
        self.radio_button_layout.addWidget(self.ege_radio)

        self.final_radio = QtWidgets.QRadioButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.final_radio.setFont(font)
        self.final_radio.setObjectName("final_radio")
        self.radio_button_layout.addWidget(self.final_radio)

        self.other_radio = QtWidgets.QRadioButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.other_radio.setFont(font)
        self.other_radio.setObjectName("other_radio")
        self.radio_button_layout.addWidget(self.other_radio)

        self.essay_type_layout.addLayout(self.radio_button_layout)
        self.verticalLayout.addLayout(self.essay_type_layout)

        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.unknown_author_lbl = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.unknown_author_lbl.setFont(font)
        self.unknown_author_lbl.setObjectName("unknown_author_lbl")
        self.unknown_author_lbl.setVisible(False)
        self.gridLayout_3.addWidget(self.unknown_author_lbl, 0, 0, 1, 1)
        self.unknown_author_edit = QtWidgets.QLineEdit(parent=self.widget)
        self.unknown_author_edit.setMinimumSize(QtCore.QSize(0, 40))
        self.unknown_author_edit.setMaxLength(80)
        self.unknown_author_edit.setVisible(False)
        self.unknown_author_edit.setObjectName("unknown_author_edit")
        self.gridLayout_3.addWidget(self.unknown_author_edit, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.save_btn = QtWidgets.QPushButton(parent=self.widget)
        self.save_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.save_btn.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        self.save_btn.setFont(font)
        self.save_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout.addWidget(self.save_btn)
        self.verticalLayout_2.addWidget(self.widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.go_home_btn.setText(_translate("MainWindow", "На главную"))
        self.title.setPlaceholderText(_translate("MainWindow", "Название сочинения"))
        self.essay_text.setHtml(_translate("MainWindow",
                                           "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                           "p, li { white-space: pre-wrap; }\n"
                                           "</style></head><body style=\" font-family:\'Times New Roman\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
                                           "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.essay_text.setPlaceholderText(_translate("MainWindow", "Начните писать сочинение..."))
        self.label_2.setText(_translate("MainWindow", "1) На какую тему написано сочинение?"))
        self.label.setText(_translate("MainWindow", "2) Какие произведения вы приводили в качестве примера?"))
        self.essay_type_label.setText(_translate("MainWindow", "3) Это сочинение..."))
        self.ege_radio.setText(_translate("MainWindow", "сочинение ЕГЭ"))
        self.final_radio.setText(_translate("MainWindow", "Итоговое сочинение"))
        self.other_radio.setText(_translate("MainWindow", "другое"))
        self.unknown_author_lbl.setText(_translate("MainWindow", "Кто написал ?"))
        self.save_btn.setText(_translate("MainWindow", "Сохранить сочинение "))